# Generated by Django 4.1.11 on 2024-10-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthtips', '0002_rename_healthtips_healthtip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='blog_post',
            new_name='tip',
        ),
    ]
