# Generated by Django 4.1.11 on 2024-10-03 14:21

from django.db import migrations, models
import pharmacy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1500)),
                ('best_use', models.CharField(max_length=1500)),
                ('instructions', models.CharField(max_length=1500)),
                ('expiry_date', models.DateField()),
                ('manufacturing_date', models.DateField()),
                ('batch_no', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('manufacturing_country', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=pharmacy.models.drug_directory_path)),
            ],
        ),
    ]
