# Generated by Django 4.1.11 on 2024-10-02 20:26

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.doctor_directory_path)),
                ('specialization', models.CharField(max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,13}$', 'Enter a valid phone number.')])),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=300)),
                ('graduation_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Enter a valid year.')])),
                ('days', models.CharField(blank=True, max_length=255)),
                ('work_from', models.TimeField()),
                ('work_to', models.TimeField()),
                ('about', models.TextField(max_length=1000)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
