# Generated by Django 4.1.11 on 2024-10-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='case',
            new_name='caseInfo',
        ),
    ]
